name: automech-env

channels:
    - pacchem
    - rdkit
    - openbabel

dependencies:
    - python
    - more-itertools
    - numpy
    - pandas
    - pyyaml
    - pytest
    - pytest-cov
    - flake8
    - pylint
    - pacchem::autoparse
    - pacchem::autocom
    - pacchem::automol
