jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev  # needed for matplotlib
                    conda env create -f environment.yml
            - run:
                name: Run tests
                command: |
                    source activate automech-env
                    python setup.py install
                    cd examples
                    pytest -v --cov=automechanic --pyargs automechanic
                    flake8 --exit-zero automechanic
                    pylint --rcfile=../.pylintrc automechanic
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
